### PR TITLE
Test ability to store an RDF document with named graphs (quads) in it

### PR DESCRIPTION
**Pull request by michielbdejong**
Fixes https://github.com/solid-contrib/test-suite/issues/158

### CODE REVIEW

**Comment by michielbdejong** [comment]
Using the clarifications from #102 plus the `css.env` file from https://github.com/solid-contrib/conformance-test-harness/blob/main/USAGE.md#minimal-example I can now run the required tests with:
```
./run.sh -d . css --filter=content-negotiation
```

**Review by edwardsph — COMMENTED** [review]
LGTM
One thing I wanted to check was whether the parse and contains methods in the test harness work at the quad or triple level. If only triple, then the test would not prove that we got the graph back intact but I think we are OK as the implementation tests the models using graph isomorphism: https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/model/util/Models.html#isomorphic(java.lang.Iterable,java.lang.Iterable)

It might be worth proving this in a quick test by loading a second resource with a different context as the expected value and then confirming the tests fail. What do you think?

**Comment by edwardsph** [comment]
@michielbdejong @pchampin @csarven Whilst this test does what we originally expected, I'm now considering whether the test is a valid representation of the requirement. As mentioned in https://github.com/solid-contrib/test-suite/issues/158 the quads represented by the JSON-LD resource are:
```
<http://example.org/ns/test> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org/ns/Graph>.
<http://example.org/ns/naughty> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org/ns/Trial> <http://example.org/ns/test>.
```
So there is one triple in the default graph and one in a named graph.

Going through the specs:
* The [Solid spec](https://solidproject.org/TR/protocol#resource-representations) refers to the resource as an RDF Document
* [RDF 1.1 Concepts](https://www.w3.org/TR/rdf11-concepts/#h3_rdf-documents) says this can be an RDF graph or an RDF dataset
* The [Solid spec](https://solidproject.org/TR/protocol#resource-representations) says the server must accept GET requests with Turtle or JSON-LD accept headers
* The problem is that whilst JSON-LD can encode a dataset, Turtle cannot so what should the server do?
  * Only return the triples in the default graph
  * Return the triples from the union of the default graph and all named graphs

[RDF 1.1 Concepts](https://www.w3.org/TR/rdf11-concepts/#section-dataset-conneg) gives us a guide:
> Web resources may have multiple representations that are made available via [content negotiation](http://www.w3.org/TR/webarch/#frag-coneg) [[WEBARCH](https://www.w3.org/TR/rdf11-concepts/#bib-WEBARCH)]. A representation may be returned in an RDF serialization format that supports the expression of both [RDF datasets](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-dataset) and [RDF graphs](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-graph). If an [RDF dataset](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-dataset) is returned and the consumer is expecting an [RDF graph](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-graph), the consumer is expected to use the [RDF dataset's](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-dataset) default graph.

From this I would suggest that a consumer doing a `GET` with `Accept: text/turtle` is expecting an RDF graph and therefore the valid response should only contain the triples from the default graph, i.e.
```
<http://example.org/ns/test> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org/ns/Graph>.
```

If you agree with this, we will need to modify the 2nd scenario.

**Comment by kjetilk** [comment]
This is an issue that has had too many assumptions in the past, and I have not been sufficiently active to know if it has been resolved. The issue that I started for this discussion is in https://github.com/solid/specification/issues/291

Back in the day, the notion was that the graph was identified with the document, and thus had to be an information resource. I think NSS was developed with that notion, and thus contained only triples.

It seems to me that the VC JSON-LD was designed around the notion of trees, and thus that it ended up a quad was a consequence of tree-thinking, not of knowledge graph engineering. Nevertheless, it also seems to me that having just triples in the documents is a lost cause by now.

I think it is unfortunate, because it made a lot of sense to just use a quad store to implement this stuff. My guess is that this will lead to abandoning RDF down the road.

**Pull request merged**
